---
- name: Demo Playbook
  remote_user: ubuntu
  become: true
  become_user: root
  become_method: sudo
  hosts: target
  vars:
    ansible_python_interpreter: /usr/bin/python3
    ansible_host_key_checking: false
    ansible_stdout_callback: yaml
  
  pre_tasks:
    - name: Wait for the target to become alive
      wait_for_connection:
        timeout: 60

    - name: Install Python 3 for Ansible
      become: true
      apt:
        name: 'python3'
        update_cache: yes

  roles:
    - install-nodejs
    - deploy-nodejs-server
